using SolhigsonAspnetCoreApp.Domain.Interfaces;

namespace SolhigsonAspnetCoreApp.Domain.Dto;

/*
 * Generated on: 24-Feb-2022 10:19:48 UTC
 * Generated by: Solhigson.Framework.efcoretool
 *
 * https://github.com/solhigson-public/solhigson.framework
 * https://www.nuget.org/packages/solhigson.framework.efcoretool
 *
 * This file is never overwritten, place custom code here
 */
public partial record CountryDto : IDtoUpdateModel
{
}