using System;

namespace SolhigsonAspnetCoreApp.Domain.Dto
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial record InstitutionDto
    { 
		public string Name { get; set; }
		public bool EnablePortalAccess { get; set; }
		public string Id { get; set; }
		public System.DateTime Created { get; set; }
		public System.DateTime Updated { get; set; }

    }
}