using System;

namespace SolhigsonAspnetCoreApp.Domain.CacheModels
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial record CountryCacheModel
    { 
		public string Code { get; set; }
		public string Name { get; set; }
		public string Id { get; set; }

    }
}