#nullable enable
using System;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Solhigson.Framework.Infrastructure;

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class CountryRepository : SolhigsonAspnetCoreAppCachedRepositoryBase<SolhigsonAspnetCoreApp.Domain.Entities.Country
        ,SolhigsonAspnetCoreApp.Domain.CacheModels.CountryCacheModel>, 
            SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.ICountryRepository
    {
        public CountryRepository(SolhigsonAspnetCoreApp.Infrastructure.AppDbContext dbContext) : base(dbContext)
        {
        }

		public virtual async Task<SolhigsonAspnetCoreApp.Domain.Entities.Country?> GetByIdAsync(string id)
		{
			if (id is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Id == id;
			return await Where(query).FirstOrDefaultAsync();
		}

		public virtual async Task<TK?> GetByIdAsync<TK>(string id) where TK : class
		{
			if (id is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Id == id;
			return await Where<TK>(query).FirstOrDefaultAsync();
		}

		public virtual async Task<SolhigsonAspnetCoreApp.Domain.Entities.Country?> GetByCodeAsync(string code)
		{
			if (code is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Code == code;
			return await Where(query).FirstOrDefaultAsync();
		}

		public virtual async Task<TK?> GetByCodeAsync<TK>(string code) where TK : class
		{
			if (code is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Code == code;
			return await Where<TK>(query).FirstOrDefaultAsync();
		}


		//Cached Methods
		public virtual async Task<SolhigsonAspnetCoreApp.Domain.CacheModels.CountryCacheModel?> GetByIdCachedAsync(string id)
		{
			if (id is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Id == id;
			return await GetSingleCachedAsync(query);
		}

		public virtual async Task<TK?> GetByIdCachedAsync<TK>(string id) where TK : class
		{
			if (id is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Id == id;
			return await GetSingleCachedAsync<TK>(query);
		}

		public virtual async Task<SolhigsonAspnetCoreApp.Domain.CacheModels.CountryCacheModel?> GetByCodeCachedAsync(string code)
		{
			if (code is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Code == code;
			return await GetSingleCachedAsync(query);
		}

		public virtual async Task<TK?> GetByCodeCachedAsync<TK>(string code) where TK : class
		{
			if (code is null) { return null; }

			Expression<Func<SolhigsonAspnetCoreApp.Domain.Entities.Country, bool>> query = 
				t => t.Code == code;
			return await GetSingleCachedAsync<TK>(query);
		}


    }
}