#nullable enable

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class SolhigsonAspnetCoreAppRepositoryBase<T> : Solhigson.Framework.Data.Repository.RepositoryBase<T, SolhigsonAspnetCoreApp.Infrastructure.AppDbContext>, 
        SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.ISolhigsonAspnetCoreAppRepositoryBase<T> where T : class, new()
    {
        public SolhigsonAspnetCoreAppRepositoryBase(SolhigsonAspnetCoreApp.Infrastructure.AppDbContext dbContext) : base(dbContext)
        {
        }
    }
}