#nullable enable

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class SolhigsonAspnetCoreAppCachedRepositoryBase<T, TCacheModel> 
        : Solhigson.Framework.Data.Repository.CachedRepositoryBase<T, SolhigsonAspnetCoreApp.Infrastructure.AppDbContext, TCacheModel> 
        where T : class, new() where TCacheModel : class
    {
        public SolhigsonAspnetCoreAppCachedRepositoryBase(SolhigsonAspnetCoreApp.Infrastructure.AppDbContext dbContext) : base(dbContext)
        {
        }
    }
}