#nullable enable
using System.Threading.Tasks;

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface IInstitutionRepository 
        : SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.ISolhigsonAspnetCoreAppCachedRepositoryBase<SolhigsonAspnetCoreApp.Domain.Entities.Institution
            ,SolhigsonAspnetCoreApp.Domain.CacheModels.InstitutionCacheModel>
    {
		Task<SolhigsonAspnetCoreApp.Domain.Entities.Institution?> GetByIdAsync(string id);
		Task<TK?> GetByIdAsync<TK>(string id) where TK : class;
		Task<SolhigsonAspnetCoreApp.Domain.Entities.Institution?> GetByNameAsync(string name);
		Task<TK?> GetByNameAsync<TK>(string name) where TK : class;

		//Cached Methods
		Task<SolhigsonAspnetCoreApp.Domain.CacheModels.InstitutionCacheModel?> GetByIdCachedAsync(string id);
		Task<TK?> GetByIdCachedAsync<TK>(string id) where TK : class;
		Task<SolhigsonAspnetCoreApp.Domain.CacheModels.InstitutionCacheModel?> GetByNameCachedAsync(string name);
		Task<TK?> GetByNameCachedAsync<TK>(string name) where TK : class;
    
    }
}