#nullable enable

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface IRepositoryWrapper
    {
        SolhigsonAspnetCoreApp.Infrastructure.AppDbContext DbContext { get; }
        System.Threading.Tasks.Task SaveChangesAsync();
        int SaveChanges();
		SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.ICountryRepository CountryRepository { get; }
		SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.ICurrencyRepository CurrencyRepository { get; }
		SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions.IInstitutionRepository InstitutionRepository { get; }

    }
}