#nullable enable

namespace SolhigsonAspnetCoreApp.Infrastructure.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface ISolhigsonAspnetCoreAppCachedRepositoryBase<T, TCacheModel> 
        : Solhigson.Framework.Data.Repository.ICachedRepositoryBase<T, TCacheModel> 
        where T : class, new() where TCacheModel : class
    {
    }
}